### ISSUE TITLE
GitHub Personal Access Token: clarify the permissions needed

### ISSUE THREAD

**Issue by LolloneS** [projectkerberus/kerberus-dashboard#11]
As of now, the permissions the PAT needs are not specified. Following a least-privilege approach, it would be useful to know which boxes to tick when creating it from GitHub's UI.

**Comment by Giglium** [comment]
Hi @LolloneS,
We moved from PAT to Github App. As you can see in the [Kerberus Platform Tutorial](https://github.com/projectkerberus/kerberus-platform/blob/main/INSTALL.md), we follow the least-privilege approach and we specify all the needed permissions.
